import Head from 'next/head'
import {Heading} from "@chakra-ui/react"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading>Roastedcoffee</Heading>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vitae beatae sint fugit possimus architecto culpa non deserunt accusamus cumque voluptatem?</p>
      </main>
    </>
  )
}
